trigger: none

parameters:
- name: org
  type: string
  displayName: "Organization [O]"
  default: "MCCORP"
- name: ou
  type: string
  displayName: "Organizational Unit [OU]"
  default: "IT"
- name: cn
  type: string
  displayName: "Common Name [CN]"
  default: "test.example.com"
- name: sans
  type: object
  displayName: "Subject Alternative Names [SANs]"
  default:
  - '*.example.com'
  - '*.test.example.com'

## Here we recover the secure vars and files for them to be available in the pipeline

stages:
- stage: sign_certificate
  displayName: Generate Signed Certificate
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: sign_certificate_job 
    displayName: Sign and Upload Certificate
    variables:
    - group: rootCAvars
    - name: rootCAkeypass
      value: $[variables.rootCAkeypass]
    steps:
    - script: ls -la
      displayName: 'Checking contents of folder'
    - task: DownloadSecureFile@1
      name: cacrt
      displayName: 'Download CA root certificate'
      inputs:
        secureFile: 'rootCA.crt'
    - task: DownloadSecureFile@1
      name: cakey
      displayName: 'Download CA private key'
      inputs:
        secureFile: 'rootCA.key'
    - script: ls -la
      displayName: 'Checking again contents of folder'
