name: Signed Certificate Creation
run-name: Creating a certificate signed by my own CA
on: 
  workflow_dispatch:
    inputs:
      org:
        description: 'Organization'
        required: true
        default: 'MCCORP'
      orgunit:
        description: 'Organizational Unit'
        required: true
        default: 'IT'
      cn:
        description: 'Common Name'
        required: true
        default: 'test.example.com'
jobs:
  Create-Upload-Certificate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve the CA and key and decode to files
        env:
          CA_BASE64: ${{ secrets.ROOT_CA }}
          CA_PKEY_BASE64: ${{ secrets.ROOT_CA_KEY }}
        run: |
          echo $CA_BASE64 | base64 --decode > rootCA.crt
          echo $CA_PKEY_BASE64 | base64 --decode > rootCA.key
      - name: Add execute permission to script
        run: chmod +x create-signed-certificate.sh
      - name: Create signed certificate
        run: ./create-signed-certificate.sh ${{ inputs.org }} ${{ inputs.orgunit }} ${{ inputs.cn }}
      - name: Create archive for upload
        env:
          CN: ${{ inputs.cn }}
        run: |
          DIR=${CN//[-._]/}
          zip -r $DIR.zip $DIR
          ls -la 
          ls -la ./$DIR/